version: 2.1
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "11.5.0"

    steps:
      - checkout

    # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

    # Run scheme and project
      - run:
          # run our tests using xcode's cli tool `xcodebuild`
          name: Run Unit Tests
          command: xcodebuild -list && xcodebuild -workspace loafwallet.xcworkspace -scheme loafwallet -configuration Debug -destination "platform=iOS Simulator,name=iPhone 8"   clean test
